// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqmilkkzjprquqkvrcyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxbWlsa2t6anBycXVxa3ZyY3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTQ1OTYsImV4cCI6MjA2NjY3MDU5Nn0.GCGXpmYDLgDoRQ6rosK_exoGVX3uT_bDwxwDS5abSr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);